!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.2.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_sorting_module_mergesort (a, work, ax, f2py_a_&
     &d0, f2py_a_d1, f2py_work_d0, f2py_work_d1)
      use sorting_module, only : mergesort
      use ira_precision
      integer(kind=ip) ax
      integer f2py_a_d0
      integer f2py_a_d1
      integer f2py_work_d0
      integer f2py_work_d1
      real(kind=rp) a(f2py_a_d0,f2py_a_d1)
      real(kind=rp) work(f2py_work_d0,f2py_work_d1)
      call mergesort(a, work, ax)
      end subroutine f2pywrap_sorting_module_mergesort
      
      subroutine f2pyinitsorting_module(f2pysetupfunc)
      interface 
      subroutine f2pywrap_sorting_module_mergesort (a, work, ax, f2py_a_&
     &d0, f2py_a_d1, f2py_work_d0, f2py_work_d1)
      use ira_precision
      integer(kind=ip) ax
      integer f2py_a_d0
      integer f2py_a_d1
      integer f2py_work_d0
      integer f2py_work_d1
      real(kind=rp) a(f2py_a_d0,f2py_a_d1)
      real(kind=rp) work(f2py_work_d0,f2py_work_d1)
      end subroutine f2pywrap_sorting_module_mergesort
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_sorting_module_mergesort)
      end subroutine f2pyinitsorting_module

      subroutine f2pywrap_err_module_get_err_msg (get_err_msgf2pywrap, i&
     &err)
      use err_module, only : get_err_msg
      use ira_precision
      integer(kind=ip) ierr
      character(len=512) get_err_msgf2pywrap
      get_err_msgf2pywrap = get_err_msg(ierr)
      end subroutine f2pywrap_err_module_get_err_msg
      
      subroutine f2pyiniterr_module(f2pysetupfunc)
      use err_module, only : err_too_small_kmax
      use err_module, only : err_other
      use err_module, only : err_beta
      use err_module, only : err_svd
      use err_module, only : err_determinant
      use err_module, only : err_acos_arg
      use err_module, only : err_size_nmax
      use err_module, only : err_list_too_small
      use err_module, only : err_unknown_op
      interface 
      subroutine f2pywrap_err_module_get_err_msg (get_err_msgf2pywrap, i&
     &err)
      use ira_precision
      integer(kind=ip) ierr
      character(len=512) get_err_msgf2pywrap
      end subroutine f2pywrap_err_module_get_err_msg
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(err_too_small_kmax,err_other,err_beta,err_svd,e&
     &rr_determinant,err_acos_arg,err_size_nmax,err_list_too_small,err_u&
     &nknown_op,f2pywrap_err_module_get_err_msg)
      end subroutine f2pyiniterr_module

      
      subroutine f2pyinitira_pbc(f2pysetupfunc)
      use ira_pbc, only : pbc_vec
      external f2pysetupfunc
      call f2pysetupfunc(pbc_vec)
      end subroutine f2pyinitira_pbc

      subroutine f2pywrap_sofi_tools_gcd_rec (gcd_recf2pywrap, u, v)
      use sofi_tools, only : gcd_rec
      use ira_precision
      integer(kind=ip) u
      integer(kind=ip) v
      integer gcd_recf2pywrap
      gcd_recf2pywrap = gcd_rec(u, v)
      end subroutine f2pywrap_sofi_tools_gcd_rec
      subroutine f2pywrap_sofi_tools_check_pg_nop (check_pg_nopf2pywrap,&
     & pg, nop)
      use sofi_tools, only : check_pg_nop
      use ira_precision
      integer(kind=ip) nop
      character(len=10) pg
      integer(kind=ip) check_pg_nopf2pywrap
      check_pg_nopf2pywrap = check_pg_nop(pg, nop)
      end subroutine f2pywrap_sofi_tools_check_pg_nop
      subroutine f2pywrap_sofi_tools_get_expected_nop (get_expected_nopf&
     &2pywrap, pg)
      use sofi_tools, only : get_expected_nop
      use ira_precision
      character(len=*) pg
      integer(kind=ip) get_expected_nopf2pywrap
      get_expected_nopf2pywrap = get_expected_nop(pg)
      end subroutine f2pywrap_sofi_tools_get_expected_nop
      subroutine f2pywrap_sofi_tools_find_inversion (find_inversionf2pyw&
     &rap, nbas, op)
      use sofi_tools, only : find_inversion
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      logical find_inversionf2pywrap
      find_inversionf2pywrap = .not.(.not.find_inversion(nbas, op))
      end subroutine f2pywrap_sofi_tools_find_inversion
      subroutine f2pywrap_sofi_tools_find_sigma (find_sigmaf2pywrap, nba&
     &s, op, n_int)
      use sofi_tools, only : find_sigma
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      integer(kind=ip) n_int(nbas)
      logical find_sigmaf2pywrap
      find_sigmaf2pywrap = .not.(.not.find_sigma(nbas, op, n_int))
      end subroutine f2pywrap_sofi_tools_find_sigma
      subroutine f2pywrap_sofi_tools_find_cn (find_cnf2pywrap, nbas, op,&
     & n_int)
      use sofi_tools, only : find_cn
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      integer(kind=ip) n_int(nbas)
      logical find_cnf2pywrap
      find_cnf2pywrap = .not.(.not.find_cn(nbas, op, n_int))
      end subroutine f2pywrap_sofi_tools_find_cn
      subroutine f2pywrap_sofi_tools_op_valid_ext_b (op_valid_ext_bf2pyw&
     &rap, rmat, bfield)
      use sofi_tools, only : op_valid_ext_b
      use ira_precision
      real(kind=rp) rmat(3,3)
      real(kind=rp) bfield(3)
      logical op_valid_ext_bf2pywrap
      op_valid_ext_bf2pywrap = .not.(.not.op_valid_ext_b(rmat, bfield))
      end subroutine f2pywrap_sofi_tools_op_valid_ext_b
      
      subroutine f2pyinitsofi_tools(f2pysetupfunc)
      use sofi_tools, only : nmax
      use sofi_tools, only : m_thr
      use sofi_tools, only : op_error
      use sofi_tools, only : op_identity
      use sofi_tools, only : op_inversion
      use sofi_tools, only : op_prop_rot
      use sofi_tools, only : op_improp_rot
      use sofi_tools, only : op_mirror
      use sofi_tools, only : pi
      use sofi_tools, only : epsilon
      use sofi_tools, only : collinearity_thr
      use sofi_tools, only : lim_n_val
      use sofi_tools, only : cross_prod
      use sofi_tools, only : matrix_distance
      use sofi_tools, only : md
      use sofi_tools, only : diag
      use sofi_tools, only : construct_reflection
      use sofi_tools, only : construct_rotation
      use sofi_tools, only : ax_convention
      interface 
      subroutine f2pywrap_sofi_tools_gcd_rec (gcd_recf2pywrap, u, v)
      use ira_precision
      integer(kind=ip) u
      integer(kind=ip) v
      integer gcd_recf2pywrap
      end subroutine f2pywrap_sofi_tools_gcd_rec 
      subroutine f2pywrap_sofi_tools_check_pg_nop (check_pg_nopf2pywrap,&
     & pg, nop)
      use ira_precision
      integer(kind=ip) nop
      character(len=10) pg
      integer(kind=ip) check_pg_nopf2pywrap
      end subroutine f2pywrap_sofi_tools_check_pg_nop 
      subroutine f2pywrap_sofi_tools_get_expected_nop (get_expected_nopf&
     &2pywrap, pg)
      use ira_precision
      character(len=*) pg
      integer(kind=ip) get_expected_nopf2pywrap
      end subroutine f2pywrap_sofi_tools_get_expected_nop 
      subroutine f2pywrap_sofi_tools_find_inversion (find_inversionf2pyw&
     &rap, nbas, op)
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      logical find_inversionf2pywrap
      end subroutine f2pywrap_sofi_tools_find_inversion 
      subroutine f2pywrap_sofi_tools_find_sigma (find_sigmaf2pywrap, nba&
     &s, op, n_int)
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      integer(kind=ip) n_int(nbas)
      logical find_sigmaf2pywrap
      end subroutine f2pywrap_sofi_tools_find_sigma 
      subroutine f2pywrap_sofi_tools_find_cn (find_cnf2pywrap, nbas, op,&
     & n_int)
      use ira_precision
      integer(kind=ip) nbas
      character(len=1) op(nbas)
      integer(kind=ip) n_int(nbas)
      logical find_cnf2pywrap
      end subroutine f2pywrap_sofi_tools_find_cn 
      subroutine f2pywrap_sofi_tools_op_valid_ext_b (op_valid_ext_bf2pyw&
     &rap, rmat, bfield)
      use ira_precision
      real(kind=rp) rmat(3,3)
      real(kind=rp) bfield(3)
      logical op_valid_ext_bf2pywrap
      end subroutine f2pywrap_sofi_tools_op_valid_ext_b
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(nmax,m_thr,op_error,op_identity,op_inversion,op&
     &_prop_rot,op_improp_rot,op_mirror,pi,epsilon,collinearity_thr,lim_&
     &n_val,cross_prod,f2pywrap_sofi_tools_gcd_rec,matrix_distance,md,di&
     &ag,f2pywrap_sofi_tools_check_pg_nop,f2pywrap_sofi_tools_get_expect&
     &ed_nop,f2pywrap_sofi_tools_find_inversion,f2pywrap_sofi_tools_find&
     &_sigma,f2pywrap_sofi_tools_find_cn,f2pywrap_sofi_tools_op_valid_ex&
     &t_b,construct_reflection,construct_rotation,ax_convention)
      end subroutine f2pyinitsofi_tools


